Add simple_calculator.py
ary1733/Hacktober2020 pull request #41
Opened 2020-10-11 16:57 UTC by muhesh-kumar

I have added simple_calculator.py, which is a simple calculator written in Python. Hope you like it!

2020-10-11 18:32 UTC, ary1733 commented on Python/simple_calculator.py
> +    print("The quotient is:", a / b)
check b!=0

2020-10-11 18:32 UTC, ary1733 requested changes
whenever a calculator divides you must check b!=0

2020-10-12 03:36 UTC, muhesh-kumar commented
Hello @ary1733 ! I have modified the code to handle division by 0. Kindly check.

2020-10-12 06:46 UTC, ary1733 approved these changes

2020-10-12 06:47 UTC, merged